---
ChatBotAgent:
  lex_config:
    bot_name: PuppetBot
    bot_alias: puppetmoster
    user_id: 00001
    content_type: "audio/l16; rate=16000; channels=1"
  polly_config:
    voice_id: Ivy

MPG321AudioPlayer:
  player_offset: 100          # ms

CognitoAuthenticator:
  username: xxxxx
  password: xxxxx
  cognito_pool_id: xxxxx
  client_id: xxxxx
  identity_pool_id: xxxxx
  region_name: xxxxx